import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import "@repo/ui/index.css"
import { ThemeProvider } from "./components/theme-provider";
import {Navigation} from "@repo/ui/widgets/Navigation.tsx"
// import { ModeToggle } from "@repo/ui/widgets/modeToggle.tsx";
import { ModeToggle } from "./components/modeTheme";
import {ReduxProvider} from "@repo/redux-utils/libs/provider";
import Footer from "@repo/ui/widgets/footer.tsx";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
              <Navigation>
                <ModeToggle/>
              </Navigation>
                {children}
              <Footer className="mt-4 rounded-none"/>
          </ThemeProvider> 
        </ReduxProvider>
      </body>
    </html>
  );
}
