import { ThemeProvider } from "@repo/ui/widgets/theme-provider";
import { ReduxProvider } from "@repo/redux-utils/libs/provider";
import { Toaster } from "@repo/ui/components/ui/toaster";
import type { Metadata } from "next";
import localFont from "next/font/local";
import HolyLoader from "holy-loader";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";
import { SearchInput } from "./(new)/categories/_components/search-input";
import { parseAsString, useQueryStates } from "nuqs";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,params
}: Readonly<{
  children: React.ReactNode;
  params:Promise<{q:string}>
}>) {
  const par=await params;
    // const [q] = useQueryStates({ search: parseAsString.withDefault("") });
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <HolyLoader />
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <NuqsAdapter>
              <header className="sticky top-0 z-50 border-b px-6 py-3">
                <div className="max-w-7xl mx-auto flex items-center justify-between">
                    <h2 className="text-xl font-bold text-primary">TechStore</h2>
                    <SearchInput defaultValue={par.q} />
                    {/* <div className="flex gap-4"> 
                        </div> */}
                </div>
              </header>
              {children}
            </NuqsAdapter>
            <Toaster />
          </ThemeProvider> 
        </ReduxProvider>
      </body>
    </html>
  );
}
